"""A page of their own for every creator: thesitrep.gg/leissik, thesitrep.gg/sammymedows.

Each one is docs/loadouts/index.html with the creator pinned (window.DF_LOADOUTS_CREATOR) and its
own title and description, so a link to it unfurls in a chat as that person's builds rather than
as "Loadouts". The address is the creator's name as they write it, squeezed to letters and digits,
because that is what somebody types; where the internal id is different (medow for SammyMedows)
the id gets a page too, which only forwards.

build.py calls this on every run it writes or finds unchanged, so a creator added to creators.json
has a page the same morning and one removed loses it. Run it on its own after changing the
template (docs/loadouts/index.html) to regenerate them all:  python3 pages.py
"""
import json, os, re, html, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.normpath(os.path.join(HERE, '..', '..', 'docs'))
TEMPLATE = os.path.join(DOCS, 'loadouts', 'index.html')
MARK = '<!-- generated by tools/loadouts/pages.py from loadouts/index.html; edit that, not this -->'
# Top-level names the site already uses or may want. A creator whose name lands on one of these
# gets no page of their own (the card links to their ?creator= view instead) rather than a page
# that shadows part of the site.
RESERVED = {'loadouts', 'data', 'img', 'tabs', 'events', 'connect', 'board', 'admin', 'index',
            'app', 'config', 'api', 'about', 'privacy', 'terms', 'help', 'login', 'join', 'invite'}

slug_of = lambda name: re.sub(r'[^a-z0-9]', '', (name or '').lower())


def assign(creators):
    """Set creators[id]['page'] to the creator's own address ("leissik/"), or remove it."""
    taken = set()
    for cid, c in creators.items():
        s = slug_of(c.get('name')) or slug_of(cid)
        if s in RESERVED or s in taken or os.path.exists(os.path.join(DOCS, s)) and not _ours(s):
            c.pop('page', None)
            continue
        taken.add(s)
        c['page'] = s + '/'
    return creators


def _ours(d):
    f = os.path.join(DOCS, d, 'index.html')
    return os.path.isfile(f) and MARK in open(f, encoding='utf-8').read(400)


def write(creators, builds):
    tpl = open(TEMPLATE, encoding='utf-8').read()
    want = {}
    for cid, c in creators.items():
        if not c.get('page'):
            continue
        slug = c['page'].rstrip('/')
        mine = [b for b in builds if b['creator'] == cid]
        want[slug] = page(tpl, cid, c, len(mine), len({b['weapon'] for b in mine}))
        if slug_of(cid) != slug and slug_of(cid) not in RESERVED:
            want.setdefault(slug_of(cid), forward(slug))
    for slug, text in want.items():
        d = os.path.join(DOCS, slug)
        if os.path.exists(d) and not _ours(slug):
            continue
        os.makedirs(d, exist_ok=True)
        f = os.path.join(d, 'index.html')
        if not os.path.exists(f) or open(f, encoding='utf-8').read() != text:
            open(f, 'w', encoding='utf-8').write(text)
    # A creator who has left takes their page with them — but only a page this file made.
    for d in os.listdir(DOCS):
        if d not in want and _ours(d):
            shutil.rmtree(os.path.join(DOCS, d))
    return sorted(want)


def page(tpl, cid, c, n, m):
    name = html.escape(c['name'])
    title = '%s · Loadouts · Sitrep' % name
    desc = html.escape('%s\'s Delta Force weapon builds with their import codes: %d %s across %d %s, '
                       'each linked to %s\'s own page.' % (c['name'], n, 'build' if n == 1 else 'builds',
                                                          m, 'weapon' if m == 1 else 'weapons', c['name']))
    t = tpl.replace('<!doctype html>\n', '<!doctype html>\n' + MARK + '\n', 1)
    t = re.sub(r'<title>[^<]*</title>', '<title>%s</title>' % title, t, count=1)
    t = re.sub(r'(<meta property="og:title" content=")[^"]*', r'\g<1>' + title, t, count=1)
    t = re.sub(r'(<meta name="description" content=")[^"]*', lambda x: x.group(1) + desc, t, count=1)
    t = re.sub(r'(<meta property="og:description" content=")[^"]*', lambda x: x.group(1) + desc, t, count=1)
    # The person, not "Loadouts", heads the page — and is there before any script has run, so the
    # name is what a reader sees first and what a link preview or a search engine reads.
    face = ('<img class="lp-av" src="%s" alt="" width="148" height="148">' % html.escape(c['avatar'])
            if c.get('avatar') else '<span class="lp-av none" aria-hidden="true">%s</span>' % html.escape(c['name'][:1].upper()))
    prof = ('<section class="lp" id="profile">%s<div class="lp-id"><div class="eyebrow"><i></i><span>Creator · Delta Force builds</span></div>'
            '<h1 class="lp-name" style="--len:%d">%s</h1></div></section>') % (face, len(c['name']), name)
    t, k = re.subn(r'<!-- hero:.*?<!-- /hero -->', lambda _: prof, t, count=1, flags=re.S)
    assert k == 1, 'no hero marker in ' + TEMPLATE
    pin = '<script>window.DF_LOADOUTS_CREATOR = %s;</script>\n' % json.dumps(cid)
    t = t.replace('<script src="tabs/loadouts.js', pin + '<script src="tabs/loadouts.js', 1)
    assert pin in t and MARK in t, 'template changed shape: ' + TEMPLATE
    return t


def forward(slug):
    return ('<!doctype html>\n%s\n<meta charset="utf-8">\n<meta http-equiv="refresh" content="0; url=../%s/">\n'
            '<link rel="canonical" href="../%s/">\n<title>Sitrep</title>\n'
            '<script>location.replace("../%s/" + location.search + location.hash)</script>\n'
            '<a href="../%s/">Moved here</a>\n') % (MARK, slug, slug, slug, slug)


if __name__ == '__main__':
    OUT = os.path.join(DOCS, 'data', 'loadouts.json')
    doc = json.load(open(OUT, encoding='utf-8'))
    assign(doc['creators'])
    json.dump(doc, open(OUT, 'w'), indent=1, ensure_ascii=False)
    print('pages', write(doc['creators'], doc['builds']))
